# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ip recipe book
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The place to keep my favourite and customized to my tastes recipes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  yuliapi
timezone: America/Los_Angeles

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin

include: ["_pages", "_posts"]
permalink: /:categories/:title/
# Version number
build: 20180621

# Exclude the following from the Jekyll build process.
# Note: "vendor" is for Travis CI.
exclude: ["vendor",
          "_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      title: YYYY-MM-DD-recipe-title.md
      output: true
      permalink: /recipe-title/
      src:
      origin:
      category: ""
      tags: ""
      ingredients:
         - ingredient1: amount


